export const FAKE_API_SEARCH = [
    {
        thumb: 'cover/7/e/6/0/7e6088a95d78a12eae1cf55d0b3cc3b9.jpg',
        artist: 'Quân A.P',
        artistIds: 'IW6ZUZI8',
        duration: '307',
        block: 'false',
        id: 'ZWADZBB9',
        hasVideo: 'true',
        streamingStatus: '1',
        thumbVideo: 'thumb_video/5/e/2/5/5e25829d61fcd6e7ae6b489194003124.jpg',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZF0BAEB8',
        zing_choice: 'false',
        name: 'Ai Là Người Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/b/0/0/3/b003deb65962e3b9b5f61f21f2f375ba.jpg',
        artist: 'Châu Khải Phong, ACV',
        artistIds: 'IWZ976C7,IW6ZAAB8',
        duration: '300',
        block: 'false',
        id: 'ZZBUE7ZA',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '',
        zing_choice: 'false',
        name: 'Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/b/1/5/7/b1571618c3e6169aef31dc6cf75d09de.jpg',
        artist: 'Lê Bảo Bình',
        artistIds: 'IWZ9B08F',
        duration: '272',
        block: 'false',
        id: 'ZUFZ0CD6',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '6BW96ZIB',
        zing_choice: 'false',
        name: 'Thương Em Đến Già',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/7/e/0/4/7e04ffa6b96ca066c39575b7d89ec6ed.jpg',
        artist: 'Hana Cẩm Tiên, Tracy Thảo My',
        artistIds: 'IW67CWB0,IWZAZWIC',
        duration: '245',
        block: 'false',
        id: 'ZZ8WWED0',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '',
        zing_choice: 'false',
        name: 'Thương Em Thiệt Hông?',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/b/9/0/1/b9014499063b9fd0a5292a5d797edd65.jpg',
        artist: 'Tân Chề',
        artistIds: 'IW78BD97',
        duration: '201',
        block: 'false',
        id: 'ZZAFWE8Z',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '',
        zing_choice: 'false',
        name: 'Thương Em Lắm',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/7/f/1/c/7f1c0611c731eea322b0c3f9291df3ac.jpg',
        artist: 'Phan Duy Anh',
        artistIds: 'IWZ99IO9',
        duration: '328',
        block: 'false',
        id: 'ZW9BAAOF',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZEFE6D79',
        zing_choice: 'false',
        name: 'Vô Cùng (Vì Anh Thương Em)',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/6/9/7/4/6974c1f14d5ac8674074a6e1ce66df4f.jpg',
        artist: 'Đinh Tùng Huy',
        artistIds: 'IWZA6F8I',
        duration: '323',
        block: 'false',
        id: 'ZWAFFDC9',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZF0C6C77',
        zing_choice: 'false',
        name: 'Anh Thương Em, Em Thương Ai',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/0/b/5/9/0b5963283fbb51afb5b93703b0705b3f.jpg',
        artist: 'Lý Tuấn Kiệt',
        artistIds: 'IWZ980FB',
        duration: '306',
        block: 'false',
        id: 'ZWAF6AUE',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZF0CUAE9',
        zing_choice: 'false',
        name: 'Ai Thật Lòng Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/2/0/f/9/20f91317e6ff0758c539eed897fdba03.jpg',
        artist: 'Saka Trương Tuyền, Lưu Hưng',
        artistIds: 'IWZ97Z8D,IWZ98BWU',
        duration: '296',
        block: 'false',
        id: 'ZZ9A78D0',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '',
        zing_choice: 'false',
        name: 'Thương Em Không',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/d/0/7/1/d071c3e20e8cfebb84943e039c337f85.jpg',
        artist: 'LyLy',
        artistIds: 'IW6WCUO8',
        duration: '274',
        block: 'false',
        id: 'ZO89BOBW',
        hasVideo: 'true',
        streamingStatus: '1',
        thumbVideo: 'thumb_video/2/3/8/f/238f493ba2ee78c79453ebe231513692.jpg',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '67UIIAWO',
        zing_choice: 'false',
        name: 'Người Ta Đâu Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'avatars/b/2/b/7/b2b7b7901a25de70e1a20e4e7dab0b03.jpg',
        artist: 'Lã., Log, TiB',
        artistIds: 'IW6ZZBDD,IW6Z7O69,IW6Z6WI7',
        duration: '193',
        block: 'false',
        id: 'ZWAF6998',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,9',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZF0CUABD',
        zing_choice: 'false',
        name: 'Anh Thương Em Nhất Mà?',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/7/c/7/3/7c73c113d151944e85487fc47ea9d606.jpg',
        artist: 'Tường Quân',
        artistIds: 'IWZ97AWA',
        duration: '202',
        block: 'false',
        id: 'ZWAE0BE9',
        hasVideo: 'true',
        streamingStatus: '1',
        thumbVideo: 'thumb_video/6/8/6/0/6860a3f0ed27763a3838ced849181e13.jpg',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZF0BE99B',
        zing_choice: 'false',
        name: 'Anh Thương Em Nhất Mà',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/5/1/a/2/51a215c16d9cac85df39f36011fc4277.jpg',
        artist: 'Chi Dân, Bảo Kun',
        artistIds: 'IWZ99099,IWZA0AUA',
        duration: '212',
        block: 'false',
        id: 'ZW9C7IDA',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,72',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZEFECUBA',
        zing_choice: 'false',
        name: 'Thương Em Thương Lắm',
        disDPlatform: '0',
    },
    {
        thumb: 'covers/4/9/4990ec75228cdd8b0a545131f98ed4a0_1503891188.jpg',
        artist: 'Jun Phạm',
        artistIds: 'IWZA6O8Z',
        duration: '270',
        block: 'false',
        id: 'ZW8IUEO9',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: 'thumb_video/8/a/8af4872ba41ae027fa8d8b86ce2fadc3_1504608242.jpg',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZEFD8UUA',
        zing_choice: 'false',
        name: 'Thương Em Hơn Chính Anh',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/b/3/9/3/b393f3f773aee54dc95709bb299593b0.jpg',
        artist: 'Huy Vạc',
        artistIds: 'IW6W86EF',
        duration: '343',
        block: 'false',
        id: 'ZUB6ODUU',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '69BOIB9Z',
        zing_choice: 'false',
        name: 'Tại Sao Anh Còn Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/f/c/3/3/fc33b26bc7f3bd1cb8ef011bcdc1c70c.jpg',
        artist: 'Hải Nam',
        artistIds: 'IW6ZBD90',
        duration: '317',
        block: 'false',
        id: 'ZWBO8W09',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '6IID8DOA',
        zing_choice: 'false',
        name: 'Chỉ Vì Quá Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'covers/b/4/b4e7aa3de6d1de07bf9f993ebd67e112_1499069028.jpg',
        artist: 'Phan Duy Anh',
        artistIds: 'IWZ99IO9',
        duration: '309',
        block: 'false',
        id: 'ZW80ZFDW',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: 'ZEFDOCAE',
        zing_choice: 'false',
        name: 'Vì Anh Thương Em',
        disDPlatform: '0',
    },
    {
        thumb: 'cover/e/3/a/b/e3abf33cb9178aeaabc95a9565ca0109.jpg',
        artist: 'Nguyễn Hữu Kha',
        artistIds: 'IW7I7A78',
        duration: '238',
        block: 'false',
        id: 'ZUIZ60DD',
        hasVideo: 'false',
        streamingStatus: '1',
        thumbVideo: '',
        genreIds: '1,8,12109',
        disable_platform_web: 'false',
        disSPlatform: '0',
        is_official: 'true',
        radioPid: '6968FBU6',
        zing_choice: 'false',
        name: 'Anh Đến Để Thương Em',
        disDPlatform: '0',
    },
];
