import song1 from '~/assets/music/listSong/1.mp3';
import song2 from '~/assets/music/listSong/2.mp3';
import song3 from '~/assets/music/listSong/3.mp3';
import song4 from '~/assets/music/listSong/4.mp3';
import song5 from '~/assets/music/listSong/5.mp3';
import song6 from '~/assets/music/listSong/6.mp3';
import song7 from '~/assets/music/listSong/7.mp3';
import song8 from '~/assets/music/listSong/8.mp3';
import song9 from '~/assets/music/listSong/9.mp3';
import song10 from '~/assets/music/listSong/10.mp3';
import song11 from '~/assets/music/listSong/11.mp3';
import song12 from '~/assets/music/listSong/12.mp3';
import song13 from '~/assets/music/listSong/13.mp3';
import song14 from '~/assets/music/listSong/14.mp3';
import song15 from '~/assets/music/listSong/15.mp3';
import song16 from '~/assets/music/listSong/16.mp3';

const ListSong = [
    {
        id: 'ZZDI9B7U',
        name: 'Vì Mẹ Anh Bắt Chia Tay',
        title: 'Vì Mẹ Anh Bắt Chia Tay',
        code: 'LHcnykkVLRWhicnyHybGkmTZXQpiDBxbi',
        content_owner: 10115,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOEEZ99',
        artists: [
            {
                name: 'Miu Lê',
                link: '/nghe-si/Vi-Me-Anh-Bat-Chia-Tay-Miu-Le-Karik-Chau-Dang-Khoa',
            },
        ],
        artists_names: 'Miu Lê, Karik, Châu Đăng Khoa',
        performer: 'Miu Lê, Karik, Châu Đăng Khoa',
        type: 'audio',
        link: song1,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/8/a/c/e/8ace218e600f48bbf5153506218d4b76.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/1/b/8/9/1b8958017b04a663eb8c093905dd4d85.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 262,
        total: 28248,
        rank_num: '',
        rank_status: 'stand',
        artist: {
            id: 'IWZ96IAC',
            name: 'Miu Lê',
            link: '/nghe-si/Miu-Le',
            cover: 'https://photo-zmp3.zmdcdn.me/cover_artist/a/5/5/b/a55b1d756d13647d5c819d6dd096bc05.jpg',
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/avatars/0/3/a/4/03a4451548668ca64e49682c02d360a3.jpg',
        },
        position: 1,
        order: '01',
        album: {
            id: '6BOEEZ99',
            link: '/album/Vi-Me-Anh-Bat-Chia-Tay-Single-Miu-Le-Karik-Chau-Dang-Khoa/6BOEEZ99.html',
            title: 'Vì Mẹ Anh Bắt Chia Tay (Single)',
            name: 'Vì Mẹ Anh Bắt Chia Tay (Single)',
            isoffical: true,
            artists_names: 'Miu Lê, Karik, Châu Đăng Khoa',
            artists: [
                {
                    name: 'Miu Lê',
                    link: '/nghe-si/Miu-Le-Karik-Chau-Dang-Khoa',
                },
            ],
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w165_r1x1_jpeg/cover/d/8/1/1/d811d20bdd4c40e9587021d4b7496d66.jpg',
            thumbnail_medium:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/cover/d/8/1/1/d811d20bdd4c40e9587021d4b7496d66.jpg',
        },
    },
    {
        id: 'ZZDZW6Z8',
        name: 'Khác Biệt To Lớn Hơn',
        title: 'Khác Biệt To Lớn Hơn',
        code: 'ZmxGtLZBDZxiklAtHtbGLHykCQWRbVcvR',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BU0UAAO',
        artists: [
            {
                name: 'Trịnh Thăng Bình',
                link: '/nghe-si/Khac-Biet-To-Lon-Hon-Trinh-Thang-Binh-Liz-Kim-Cuong',
            },
        ],
        artists_names: 'Trịnh Thăng Bình, Liz Kim Cương',
        performer: 'Trịnh Thăng Bình, Liz Kim Cương',
        type: 'audio',
        link: song2,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/9/8/f/6/98f6cf69d86e9ac4bc2d4dc5f18b3837.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/4/d/b/d/4dbd67a17030e72c036a9f98bd7ca325.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 253,
        total: 10471,
        rank_num: '',
        rank_status: 'stand',
        artist: {
            id: 'IWZ9ZD8A',
            name: 'Trịnh Thăng Bình',
            link: '/nghe-si/Trinh-Thang-Binh',
            cover: 'https://photo-zmp3.zmdcdn.me/cover_artist/6/5/5/d/655d298805d7793f86126aeadf5b86e5.jpg',
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/avatars/5/6/4/8/5648f3e886ce51f10e9de62722276222.jpg',
        },
        position: 2,
        order: '02',
        album: {
            id: '6BU0UAAO',
            link: '/album/Khac-Biet-To-Lon-Hon-Single-Trinh-Thang-Binh/6BU0UAAO.html',
            title: 'Khác Biệt To Lớn Hơn (Single)',
            name: 'Khác Biệt To Lớn Hơn (Single)',
            isoffical: true,
            artists_names: 'Trịnh Thăng Bình',
            artists: [
                {
                    name: 'Trịnh Thăng Bình',
                    link: '/nghe-si/Trinh-Thang-Binh',
                },
            ],
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w165_r1x1_jpeg/cover/8/2/f/8/82f8433545bc66ec5945660759592c37.jpg',
            thumbnail_medium:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/cover/8/2/f/8/82f8433545bc66ec5945660759592c37.jpg',
        },
    },
    {
        id: 'ZZDZ0I6D',
        name: 'Chỉ Cần Có Em',
        title: 'Chỉ Cần Có Em',
        code: 'LHcnykkdDLauCRdyGyDGZGyZhQpubdxvR',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BU0OD7U',
        artists: [
            {
                name: 'Dương Edward',
                link: '/nghe-si/Chi-Can-Co-Em-Duong-Edward',
            },
        ],
        artists_names: 'Dương Edward',
        performer: 'Dương Edward',
        type: 'audio',
        link: song3,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/4/8/d/9/48d9e8a3e31469e1b18e437910228b5d.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/2/4/1/d/241d3b8aa26111306a49d0143754e205.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 245,
        total: 9579,
        rank_num: '',
        rank_status: 'stand',
        artist: {
            id: 'IWZ97FE0',
            name: 'Dương Edward',
            link: '/nghe-si/Duong-Edward',
            cover: 'https://photo-zmp3.zmdcdn.me/cover_artist/0/3/03c0609aaec6bcc3e1a23727b0044407_1504148799.jpg',
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/avatars/f/9/6/b/f96bcce810237ef75054a9f2adf9b6f2.jpg',
        },
        position: 3,
        order: '03',
        album: {
            id: '6BU0OD7U',
            link: '/album/Chi-Can-Co-Em-Single-Duong-Edward/6BU0OD7U.html',
            title: 'Chỉ Cần Có Em (Single)',
            name: 'Chỉ Cần Có Em (Single)',
            isoffical: true,
            artists_names: 'Dương Edward',
            artists: [
                {
                    name: 'Dương Edward',
                    link: '/nghe-si/Duong-Edward',
                },
            ],
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w165_r1x1_jpeg/cover/2/4/1/d/241d3b8aa26111306a49d0143754e205.jpg',
            thumbnail_medium:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/cover/2/4/1/d/241d3b8aa26111306a49d0143754e205.jpg',
        },
    },
    {
        id: 'ZZBUE7ZA',
        name: 'Thương Em',
        title: 'Thương Em',
        code: 'ZmJHTLkdGHaQchhynyvHkmTLXWpRDVJFu',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOI6O8E',
        artists: [
            {
                name: 'Châu Khải Phong',
                link: '/nghe-si/Thuong-Em-Chau-Khai-Phong-ACV',
            },
        ],
        artists_names: 'Châu Khải Phong, ACV',
        performer: 'Châu Khải Phong, ACV',
        type: 'audio',
        link: song4,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/4/3/8/0/4380bfa57dafd052ec2d3fb695cacea2.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/b/0/0/3/b003deb65962e3b9b5f61f21f2f375ba.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 300,
        total: 9377,
        rank_num: '',
        rank_status: 'stand',
        position: 4,
        order: '04',
        album: {
            id: '6BOI6O8E',
            link: '/album/Thuong-Em-Single-Chau-Khai-Phong-ACV/6BOI6O8E.html',
            title: 'Thương Em (Single)',
            name: 'Thương Em (Single)',
            isoffical: true,
            artists_names: 'Châu Khải Phong, ACV',
            artists: [
                {
                    name: 'Châu Khải Phong',
                    link: '/nghe-si/Chau-Khai-Phong-ACV',
                },
            ],
            thumbnail:
                'https://photo-resize-zmp3.zmdcdn.me/w165_r1x1_jpeg/cover/b/0/0/3/b003deb65962e3b9b5f61f21f2f375ba.jpg',
            thumbnail_medium:
                'https://photo-resize-zmp3.zmdcdn.me/w240_r1x1_jpeg/cover/b/0/0/3/b003deb65962e3b9b5f61f21f2f375ba.jpg',
        },
    },
    {
        id: 'ZZBAFF60',
        name: 'Xin Má Rước Dâu',
        title: 'Xin Má Rước Dâu',
        code: 'LnJHykZdGSNWbVbtntFGZGyZCWQiFBJDR',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOU8CIE',
        artists: [
            {
                name: 'Diệu Kiên',
                link: '/nghe-si/Xin-Ma-Ruoc-Dau-Dieu-Kien',
            },
        ],
        artists_names: 'Diệu Kiên',
        performer: 'Diệu Kiên',
        type: 'audio',
        link: song5,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/5/d/f/2/5df2018fe6b4aaf1a67952d2fb44c9c6.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/c/4/4/c/c44c3822217d8775780358df759f126d.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 190,
        total: 8455,
        rank_num: '',
        rank_status: 'stand',
        position: 5,
        order: '05',
    },
    {
        id: 'ZZCZCWCW',
        name: 'Nhìn Mây Vẽ Người',
        title: 'Nhìn Mây Vẽ Người',
        code: 'LGxGTkZdZZcmCkHTHybHZnTkCppibdcbE',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BO96UE0',
        artists: [
            {
                name: 'Hương Ly',
                link: '/nghe-si/Nhin-May-Ve-Nguoi-Huong-Ly-Jombie-LY-M',
            },
        ],
        artists_names: 'Hương Ly, Jombie, LY.M',
        performer: 'Hương Ly, Jombie, LY.M',
        type: 'audio',
        link: song6,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/b/8/2/2/b822d5c4881e547e0ae4eeb4ee9ffb09.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/1/9/d/8/19d8b42b0aa5a00084d29c06a62556c7.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 213,
        total: 7498,
        rank_num: '',
        rank_status: 'stand',
        position: 6,
        order: '06',
    },
    {
        id: 'ZZC7BEII',
        name: 'Shay Nắnggg',
        title: 'Shay Nắnggg',
        code: 'kmxmyLZdLVLmSxLymybHkGyZXQQibdcbu',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOAOU8E',
        artists: [
            {
                name: 'AMEE',
                link: '/nghe-si/Shay-Nanggg-AMEE-Obito',
            },
        ],
        artists_names: 'AMEE, Obito',
        performer: 'AMEE, Obito',
        type: 'audio',
        link: song7,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/e/e/5/2/ee52dfa863917b8211aefd879eadca9d.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/7/0/8/4/7084f2cd75ebf35936af4d1c878e1abe.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 208,
        total: 5419,
        rank_num: '',
        rank_status: 'stand',
        position: 7,
        order: '07',
    },
    {
        id: 'ZZDWA6AE',
        name: 'Thiêu Thân',
        title: 'Thiêu Thân',
        code: 'kmJmyZLVbnbQdumymtDmknyLhWpRbdxbu',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOF0CWO',
        artists: [
            {
                name: 'B Ray',
                link: '/nghe-si/Thieu-Than-B-Ray-Sofia',
            },
        ],
        artists_names: 'B Ray, Sofia',
        performer: 'B Ray, Sofia',
        type: 'audio',
        link: song8,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/a/1/e/9/a1e9f9954b1d6a97227aab38c2de703d.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/f/e/5/6/fe5659fe70dd215e616b784bd19751b5.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 199,
        total: 4794,
        rank_num: '',
        rank_status: 'stand',
        position: 8,
        order: '08',
    },
    {
        id: 'ZZBFZ0F8',
        name: 'hai mươi hai (22)',
        title: 'hai mươi hai (22)',
        code: 'kmcHyZZBHapxFhzymybmkGtLXQWivdcbi',
        content_owner: 10115,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BO6AU68',
        artists: [
            {
                name: 'Hứa Kim Tuyền',
                link: '/nghe-si/hai-muoi-hai-22-Hua-Kim-Tuyen-AMEE',
            },
        ],
        artists_names: 'Hứa Kim Tuyền, AMEE',
        performer: 'Hứa Kim Tuyền, AMEE',
        type: 'audio',
        link: song9,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/0/a/2/f/0a2fb57ab2b5672c90d4afd352af8d2c.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/b/6/d/e/b6de6c0857b19e1c921f2d379817d491.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        mv_link: '/video-clip/hai-muoi-hai-22-Hua-Kim-Tuyen-AMEE/ZZBFZ0F8.html',
        duration: 239,
        total: 4644,
        rank_num: '',
        rank_status: 'stand',
        position: 9,
        order: '09',
    },
    {
        id: 'ZZAFI9IZ',
        name: 'Vũ Trụ Trong Anh',
        title: 'Vũ Trụ Trong Anh',
        code: 'kHxmtZLFiCEWBxLtGtbnkHtZCWWEbBJDR',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BWDFUOB',
        artists: [
            {
                name: 'Hoàng Lan',
                link: '/nghe-si/Vu-Tru-Trong-Anh-Hoang-Lan',
            },
        ],
        artists_names: 'Hoàng Lan',
        performer: 'Hoàng Lan',
        type: 'audio',
        link: song10,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/d/9/7/0/d9706814c5be9d73a15f174ce919fe0f.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/4/1/4/8/41488217c31b072ee8950b9993bd8825.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 237,
        total: 4484,
        rank_num: 1,
        rank_status: 'up',
        position: 10,
        order: 10,
    },
    {
        id: 'ZZBZA009',
        name: 'Có Không Giữ Mất Đừng Tìm',
        title: 'Có Không Giữ Mất Đừng Tìm',
        code: 'ZGcHykLdHLFBLlptHtbmkHyZCpQibBxvi',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOIC7A7',
        artists: [
            {
                name: 'Trúc Nhân',
                link: '/nghe-si/Co-Khong-Giu-Mat-Dung-Tim-Truc-Nhan',
            },
        ],
        artists_names: 'Trúc Nhân',
        performer: 'Trúc Nhân',
        type: 'audio',
        link: song11,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/d/5/1/c/d51c696d3d339ebea6d816a4e2e0dece.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/0/3/9/7/0397842eb359d014b1928c3a7ff7d548.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 216,
        total: 4178,
        rank_num: 1,
        rank_status: 'down',
        position: 11,
        order: 11,
    },
    {
        id: 'ZZDO87CU',
        name: 'Chờ Quá Lâu',
        title: 'Chờ Quá Lâu',
        code: 'ZmcnyZLBFmxBmZvTHTbmkHTLgWQEFBxvE',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOF7CC0',
        artists: [
            {
                name: 'Lê Bảo Bình',
                link: '/nghe-si/Cho-Qua-Lau-Le-Bao-Binh',
            },
        ],
        artists_names: 'Lê Bảo Bình',
        performer: 'Lê Bảo Bình',
        type: 'audio',
        link: song12,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/0/a/4/f/0a4ffd56655cac6a213034800542f0c5.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/5/4/7/4/5474f725c68ef99234147ed45df16ec8.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 295,
        total: 3951,
        rank_num: 1,
        rank_status: 'up',
        position: 12,
        order: 12,
    },
    {
        id: 'ZZ8FBUW9',
        name: 'Đám Cưới Nha?',
        title: 'Đám Cưới Nha?',
        code: 'LHxmyLkbNhBaivitmyvGZnyLhWQibVxFu',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BIFUZ9E',
        artists: [
            {
                name: 'Hồng Thanh',
                link: '/nghe-si/Dam-Cuoi-Nha-Hong-Thanh-DJ-Mie',
            },
        ],
        artists_names: 'Hồng Thanh, DJ Mie',
        performer: 'Hồng Thanh, DJ Mie',
        type: 'audio',
        link: song13,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/5/8/5/3/5853eca22fc2741d52352ba654f6e959.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/5/b/8/b/5b8b7cd3d1434afa3b2b9854efdc8756.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 175,
        total: 3945,
        rank_num: 1,
        rank_status: 'down',
        position: 13,
        order: 13,
    },
    {
        id: 'ZZAFWE8Z',
        name: 'Thương Em Lắm',
        title: 'Thương Em Lắm',
        code: 'LHxHtLkDusHGcCitHtDHLHyZhWQEDdcvu',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BWFADF8',
        artists: [
            {
                name: 'Tân Chề',
                link: '/nghe-si/Thuong-Em-Lam-Tan-Che',
            },
        ],
        artists_names: 'Tân Chề',
        performer: 'Tân Chề',
        type: 'audio',
        link: song14,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/f/b/4/9/fb4949ac1197e06ab4a6fca910976aca.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/b/9/0/1/b9014499063b9fd0a5292a5d797edd65.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 201,
        total: 3657,
        rank_num: '',
        rank_status: 'stand',
        position: 14,
        order: 14,
    },
    {
        id: 'ZZA9OZIO',
        name: 'Chờ Ngày Cưới Em',
        title: 'Chờ Ngày Cưới Em',
        code: 'knJHykZDiBmidBktHTbmkHyZhppiFdcDE',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BWBI8DW',
        artists: [
            {
                name: 'Phát Hồ',
                link: '/nghe-si/Cho-Ngay-Cuoi-Em-Phat-Ho-Huong-Ly-X2X',
            },
        ],
        artists_names: 'Phát Hồ, Hương Ly, X2X',
        performer: 'Phát Hồ, Hương Ly, X2X',
        type: 'audio',
        link: song15,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/3/5/8/d/358d14c61079baee165f3931da6d450b.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/3/8/6/8/38682a9b538219105ff3323d9d6efbb9.jpg?fs=MTY1NTkxMzAyOTE0MXx3ZWJWNHw',
        duration: 263,
        total: 3596,
        rank_num: '',
        rank_status: 'stand',
        position: 15,
        order: 15,
    },
    {
        id: 'ZZBBOZEC',
        name: 'Đoạn Tuyệt Nàng Đi (Lofi Version)',
        title: 'Đoạn Tuyệt Nàng Đi (Lofi Version)',
        code: 'LGxHyLkBmlcEkRCyHybmkHyZCppiFlQmp',
        content_owner: 7,
        isoffical: true,
        isWorldWide: true,
        playlist_id: '6BOUAZ8O',
        artists: [
            {
                name: 'Phát Huy T4',
                link: '/nghe-si/Doan-Tuyet-Nang-Di-Lofi-Version-Phat-Huy-T4',
            },
        ],
        artists_names: 'Phát Huy T4',
        performer: 'Phát Huy T4',
        type: 'audio',
        link: song16,
        lyric: 'https://static-zmp3.zmdcdn.me/lyrics/8/6/7/b/867bc8bc759ebb1da596a7c5d8b91813.lrc',
        thumbnail:
            'https://photo-resize-zmp3.zmdcdn.me/w94_r1x1_jpeg/cover/7/9/4/5/7945def0b61a268a8c5deff6bdb98346.jpg?fs=MTY1NTkxMzmUsICwNTmUsIC5MXx3ZWJWNHw',
        duration: 245,
        total: 1888,
        rank_num: '',
        rank_status: 'stand',
        position: 16,
        order: 29,
    },
];

export { ListSong };
