const ListSong = [
    {
        id: 1,
        favourite: false,
        songName: 'Cứ Chill Thôi',
        artist: ['Chillies', 'Suni Hạ Linh', 'Rhymastic'],
        path: '../assets/music/listSong1/song1.mp3',
        imgSrc: '../assets/img/music/listSong1/song1.jpg',
        album: '',
        duration: '04:30',
    },
    {
        id: 2,
        favourite: false,
        songName: 'Crush',
        artist: ['WN', 'Vani', 'An An'],
        path: './assets/music/listSong1/song2.mp3',
        imgSrc: './assets/img/music/listSong1/song2.jpg',
        album: '',
        duration: '03:18',
    },
    {
        id: 3,
        favourite: false,
        songName: 'Vô Tình',
        artist: ['Xesi', 'Hoaprox'],
        path: './assets/music/listSong1/song3.mp3',
        imgSrc: './assets/img/music/listSong1/song3.jpg',
        album: 'Vô Tình (Single)',
        duration: '04:33',
    },
    {
        id: 4,
        favourite: false,
        songName: "Because I'm Stupid",
        artist: ['SS501'],
        path: './assets/music/listSong1/song4.flac',
        imgSrc: './assets/img/music/listSong1/song4.jpg',
        album: 'Boys Over Flower OST',
        duration: '04:20',
    },
    {
        id: 5,
        favourite: false,
        songName: 'Mama Boy',
        artist: ['AMEE'],
        path: './assets/music/listSong1/song5.mp3',
        imgSrc: './assets/img/music/listSong1/song5.jpg',
        album: 'dreeAMEE',
        duration: '03:24',
    },
    {
        id: 6,
        favourite: false,
        songName: 'Cửu Vĩ Hồ',
        artist: ['Yun', 'Dr A'],
        path: './assets/music/listSong1/song6.mp3',
        imgSrc: './assets/img/music/listSong1/song6.jpg',
        album: '',
        duration: '06:05',
    },
    {
        id: 7,
        favourite: false,
        songName: 'Anh Đã Quen Với Cô Đơn',
        artist: ['Soobin Hoàng Sơn'],
        path: './assets/music/listSong1/song7.mp3',
        imgSrc: './assets/img/music/listSong1/song7.jpg',
        album: 'Anh Đã Quen Với Cô Đơn (Single)',
        duration: '03:55',
    },
    {
        id: 8,
        favourite: false,
        songName: 'Túy Âm',
        artist: ['Xesi', 'Masew', 'Nhật Nguyễn'],
        path: './assets/music/listSong1/song8.mp3',
        imgSrc: './assets/img/music/listSong1/song8.jpg',
        album: 'Túy Âm (Single)',
        duration: '03:22',
    },
    {
        id: 9,
        favourite: false,
        songName: 'Kém Duyên',
        artist: ['Rum', 'NIT', 'Masew'],
        path: './assets/music/listSong1/song9.mp3',
        imgSrc: './assets/img/music/listSong1/song9.jpg',
        album: 'Kém Duyên (Single)',
        duration: '03:44',
    },
    {
        id: 10,
        favourite: false,
        songName: 'Tình Bạn Diệu Kì',
        artist: ['AMEE', 'Ricky Star', 'Lăng LD'],
        path: './assets/music/listSong1/song10.flac',
        imgSrc: './assets/img/music/listSong1/song10.jpg',
        album: '',
        duration: '03:08',
    },
    {
        id: 11,
        favourite: false,
        songName: 'Em Có Nghe',
        artist: ['Kha'],
        path: './assets/music/listSong1/song11.mp3',
        imgSrc: './assets/img/music/listSong1/song11.jpg',
        album: '',
        duration: '04:15',
    },
    {
        id: 12,
        favourite: false,
        songName: 'Lạc Trôi',
        artist: ['Sơn Tùng M-TP'],
        path: './assets/music/listSong1/song12.mp3',
        imgSrc: './assets/img/music/listSong1/song12.jpg',
        album: '',
        duration: '03:53',
    },
    {
        id: 13,
        favourite: false,
        songName: 'Một Năm Mới Bình An',
        artist: ['Sơn Tùng MTP'],
        path: './assets/music/listSong1/song13.mp3',
        imgSrc: './assets/img/music/listSong1/song13.jpg',
        album: '',
        duration: '04:07',
    },
    {
        id: 14,
        favourite: false,
        songName: 'Hongkong1 (Official Version)',
        artist: ['Nguyễn Trọng Tài', 'San Ji', 'Double X'],
        path: './assets/music/listSong1/song14.mp3',
        imgSrc: './assets/img/music/listSong1/song14.jpg',
        album: '',
        duration: '04:13',
    },
    {
        id: 15,
        favourite: false,
        songName: 'Gác Lại Âu Lo',
        artist: ['Da LAB', 'Miu Lê'],
        path: './assets/music/listSong1/song15.mp3',
        imgSrc: './assets/img/music/listSong1/song15.jpg',
        album: '',
        duration: '04:42',
    },
    {
        id: 16,
        favourite: false,
        songName: 'Chạy Ngay Đi',
        artist: ['Sơn Tùng MTP'],
        path: './assets/music/listSong1/song16.mp3',
        imgSrc: './assets/img/music/listSong1/song16.jpg',
        album: '',
        duration: '04:08',
    },
    {
        id: 17,
        favourite: false,
        songName: 'Cùng Anh',
        artist: ['Ngọc Dolil', 'Hagi', 'STee'],
        path: './assets/music/listSong1/song17.mp3',
        imgSrc: './assets/img/music/listSong1/song17.jpg',
        album: '',
        duration: '03:17',
    },
    {
        id: 18,
        favourite: false,
        songName: 'Hãy Trao Cho Anh',
        artist: ['Sơn Tùng MTP'],
        path: './assets/music/listSong1/song18.mp3',
        imgSrc: './assets/img/music/listSong1/song18.jpg',
        album: '',
        duration: '04:05',
    },
    {
        id: 19,
        favourite: false,
        songName: 'Tộc Ca',
        artist: ['Phúc Du', 'SONBEAT'],
        path: './assets/music/listSong1/song19.mp3',
        imgSrc: './assets/img/music/listSong1/song19.jpg',
        album: '',
        duration: '03:11',
    },
    {
        id: 20,
        favourite: false,
        songName: 'Thiên Lý Ơi',
        artist: ['Jack', 'Bikay'],
        path: './assets/music/listSong1/song20.mp3',
        imgSrc: './assets/img/music/listSong1/song20.jpg',
        album: '',
        duration: '04:16',
    },
    {
        id: 21,
        favourite: false,
        songName: 'Phố Đã Lên Đèn',
        artist: ['Phố Đã Lên Đèn'],
        path: './assets/music/listSong1/song21.mp3',
        imgSrc: './assets/img/music/listSong1/song21.jpg',
        album: '',
        duration: '04:04',
    },
    {
        id: 22,
        favourite: false,
        songName: 'BlackJack',
        artist: ['Soobin', 'Binz'],
        path: './assets/music/listSong2/song20.webm',
        imgSrc: './assets/img/music/listSong2/song20.jpg',
        album: 'BlackJack (Single)',
        duration: '03:17',
    },
];
export { ListSong };
